### ISSUE TITLE
Visual separation of projects managed by self in Personal Repos tab 

### ISSUE THREAD

**Issue by fellahi-ali** [self-xdsd/self-web#329]
It would be nice to have a visual separation or indication of projects managed by **Self** in the **Personal Repos** tab, because as for now there is no clue of which repos are managed by Self; maybe adding a hint like  _managed by @ charlesmike_ for example or adding a new tab for projects _Managed by Self_ ...etc

![self-repos](https://user-images.githubusercontent.com/25110612/104239237-77e1ab00-545a-11eb-8d30-c018355936ed.png)

**Comment by charlesmike** [comment]
@fellahi-ali thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@MihaiDejeu this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-21T23:26:18.062007``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@fellahi-ali It's a good idea, I was also thinking about that. At the moment, if the user has many projects managed by Self, it's hard to remember which is which. 

But I was thinking to have a separate page for that. If the user has at least 1 Project managed by Self, then they will see the page "My Projects" in the header (between "My Repositories" and "Contributor Dashboard").

We will do it, but not right now. Let's postpone it a bit, because now we are preparing the first Prod release so we are working only on mandatory stuff.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by amihaiemil** [comment]
@fellahi-ali I implemented the `Managed Repos` tab in #341.

This is the easiest way to separate them. Having a marker for each repo on the `Personal Repos` tab would mean ``n``  more calls to the backend, for each repo.
