### ISSUE TITLE
Login Buttons On Mobile

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#353]
We added GitLab to self-web. Now, the 2 buttons look funny.

Let's try to make them a bit smaller so they fit on the same row with "Self XDSD".

![Screenshot_20210127-072240_Chrome](https://user-images.githubusercontent.com/6305156/105946812-a1145500-6070-11eb-8736-fffeb52b401c.jpg)

**Comment by charlesmike** [comment]
@Lumi3011 this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-02-06T07:24:44.193944``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by Lumi3011** [comment]
@amihaiemil As they are now, the buttons contain too much content to be placed on the same row as  "Self XDSD" and if I try to make the text smaller in order to be placed there, it won't be readable. One solution is to rename them, if you want to be on the same row, but it think that will overcrowd the logo, or, only for mobile, I could place both the logo and the buttons on center. What do you think? Let me know if you have another solution :D

**Comment by amihaiemil** [comment]
@Lumi3011 I think placing them on center for mobile will look good :D

**Comment by amihaiemil** [comment]
paid with transaction id 56V99964X3291583G

**Comment by charlesmike** [comment]
@Lumi3011 thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
