### ISSUE TITLE
Showing the invoice in a separate tab/window.

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-web#417]
It would be nice if we could have a button, besides the download one, to show the invoice in a separate tab/window.
This should apply for both PO Contracts tab invoices section and Contributor Dashboard invoices section.

![view_invoice](https://user-images.githubusercontent.com/10284893/113836149-4ba5a400-9795-11eb-9981-00c2c3d5522f.png)

**Comment by zoeself** [comment]
@criske thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by amihaiemil** [comment]
@criske Yes, I also want to do that, but I have no idea how. Pop-ups are not an option because they are not mobile friendly at all. We already have tabs on the page and creating one when clicking a button is really strange... the only option I have in mind is to create a new page for the Invoice, but that also seems a bit strange... :D

**Comment by zoeself** [comment]
@amihaiemil I couldn't find any assignee for this task. This is either because there are no contributors with role ``DEV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.

**Comment by criske** [comment]
@amihaiemil I was thinking to show them in a browser tab; it shouldn't be that hard to implement, I think :D

**Comment by amihaiemil** [comment]
@criske opening a tab with the PDF is actually not a bad idea, let's try it.

**Comment by zoeself** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-04-17T08:51:06.803683``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
