### ISSUE TITLE
LoginProducer.java:43-44: Write unit tests for...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-web#42]
The puzzle `40-0cb240ae` from #40 has to be resolved: 

https://github.com/self-xdsd/self-web/blob/55b4ca7c48c7fcbfaeb66336f1add61f30f49478/src/main/java/com/selfxdsd/selfweb/LoginProducer.java#L43-L44

The puzzle was created by cristianpela on 28-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
@amihaiemil sign me up.

**Comment by amihaiemil** [comment]
@criske This is a good ticket for a beginner on the project, I would leave it for someone else :D

**Comment by criske** [comment]
@amihaiemil While testing is easy to implement, the setup might be a little bit trickier. They will require to create their own `OAuth2AuthorizedClientService` and  `OAuth2AuthenticationToken` (this is one will be injected instead of using the sec context).
That will require other parts to used like `ClientRegistration`, `OAuth2AccessToken`, `OAuth2User`.
